# Generated by Django 4.1 on 2022-09-02 15:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCadApp', '0002_test_tutorialtest_certificate_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
