# Generated by Django 4.1 on 2022-09-02 20:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCadApp', '0003_tutorial_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
