# Generated by Django 4.1 on 2022-09-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCadApp', '0004_hint_alter_tutorial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=40, null=True)),
                ('answer2', models.CharField(max_length=40, null=True)),
                ('correct_answer', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='op1',
            new_name='optionA',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='op2',
            new_name='optionB',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='op3',
            new_name='optionC',
        ),
    ]
