# Generated by Django 4.1 on 2022-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCadApp', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
