# Generated by Django 4.1 on 2022-09-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoCadApp', '0008_alter_test_answer_alter_test_optiona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='string',
        ),
    ]
